import numpy as np
np.set_printoptions(precision=2,suppress=True)
a = np.arange(7,16,2)
print('a = ', a)
b = np.arange(10,5,-1)
print('b = ', b)
c = np.arange(15,-1,-5)
print('c = ', c)
paso = (1-0)/10
d = np.arange(0,1.1,paso)
print('d = ', d)
paso = (1-(-1))/10
e = np.arange(-1,1.1,paso)
print('e = ', e)
f = np.arange(1,2.1,0.1)
print('f = ', f)

print('\n')
a = np.linspace(7,15,5)
print('a = ', a)
b = np.linspace(10,6,5)
print('b = ', b)
c = np.linspace(15,0,4)
print('c = ', c)
d = np.linspace(0,1,11)
print('d = ', d)
e = np.linspace(-1,1,11)
print('e = ', e)
n = int((2-1)/0.1)
f = np.linspace(1,2,n+1)
print('f = ', f)